name: hashlib
description: Secure hash algorithms in pure dart
version: 1.0.0-dev.3
homepage: https://github.com/dipu-bd/hashlib

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
