name: hashlib
description: Secure hash functions, checksum generators, and key derivation algorithms optimized for Dart.
homepage: https://github.com/bitanon/hashlib
version: 1.19.2

environment:
  sdk: '>=2.14.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  hashlib_codecs: ^2.5.0

dev_dependencies:
  lints: any
  test: any
  crypto: any
  hash: any
  pointycastle: any
  benchmark_harness: any
  argon2: any

funding:
  - https://paypal.me/sd1pu
