name: hashlib
description: Python's hashlib in pure Dart
version: 1.0.0-dev.1
homepage: https://github.com/dipu-bd/hashlib

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
