name: hashlib
description: Secure hash functions, checksum generators, and key derivation algorithms optimized for Dart.
homepage: https://github.com/bitanon/hashlib
version: 1.12.1

environment:
  sdk: '>=2.14.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  hashlib_codecs: ^2.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.25.3
  crypto: ^3.0.3
  hash: ^1.0.4
  pointycastle: ^3.7.3
  benchmark_harness: ^2.2.1
  argon2: ^1.0.1

funding:
  - https://paypal.me/sd1pu
