name: hashlib
description: RFC-compliant implementations of secure hash functions in pure Dart with zero-dependencies.
version: 1.0.0-dev.4
homepage: https://github.com/dipu-bd/hashlib

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
  benchmark: ^0.3.0
  crypto: ^3.0.2
