name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check tag version matches pubspec.yaml
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          PUBSPEC_VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }' | tr -d '[:space:]')
          if [ "$TAG_VERSION" != "$PUBSPEC_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match pubspec.yaml version ($PUBSPEC_VERSION)"
            exit 1
          fi

  test:
    needs: version
    uses: ./.github/workflows/release-test.yml

  publish:
    if: github.repository == 'bitanon/hashlib'
    needs: test
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Publish - dry run
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish -f
