name: Test for Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool/package_config.json
          key: ${{ runner.os }}-test-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable', '2.19', 'beta']
        platform: ['vm', 'node']
        exclude:
          - sdk: 'beta'
            os: macos-latest
          - sdk: 'beta'
            os: windows-latest
          - platform: 'node'
            sdk: 'beta'
          - platform: 'node'
            sdk: '2.19'
            os: macos-latest
          - platform: 'node'
            sdk: '2.19'
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool/package_config.json
          key: ${{ runner.os }}-test-${{ hashFiles('**/pubspec.lock') }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test -p ${{ matrix.platform }}

  integration:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ['stable', '2.19', 'beta']
        exclude:
          # skip test on macOS/Windows for beta
          - sdk: 'beta'
            os: macos-latest
          - sdk: 'beta'
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool/package_config.json
          key: ${{ runner.os }}-test-${{ hashFiles('**/pubspec.lock') }}

      - name: Run tests
        run: |
          cd test_integration
          dart pub get
          dart run main.dart

  pana:
    if: github.repository == 'bitanon/hashlib'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install pana
        run: dart pub global activate pana

      - name: Verify with pana
        run: pana --exit-code-threshold 0
